HelloWorld/Models/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloWorld.Models
{
    public class Post
    {
        public int id { get; set; }
        public string post { get; set; }
        public DateTime postedDateTime{ get; set; }
        
    }
}

HelloWorld/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HelloWorld.Models;

namespace HelloWorld.controller
{
    public class PostController : Controller
    {
        PostContext postContext;
        public PostController(PostContext postContext)
        {
            this.postContext = postContext;
        }
        public IActionResult index()
        {
            ViewModel viewModel = new ViewModel();
            viewModel.Posts = postContext.Posts.ToArray();
            return View(viewModel);
        }
    }
}

HelloWorld/ViewComponents/PostedDataViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HelloWorld.Models;

namespace HelloWorld.ViewComponents
{

    public class PostedDataViewComponent : ViewComponent
    {
        PostContext postContext;
        public PostedDataViewComponent(PostContext postContext)
        {
            this.postContext = postContext;
        }
        public IViewComponentResult Invoke()
        {
            IEnumerable<Post> posts = postContext.Posts.ToArray();
            return View(posts);
        }
    }
}

HelloWorld/Views/Post/index.cshtml
@addTagHelper *,HelloWorld
@using HelloWorld.Models
@model ViewModel



<h3>this is index action from Post controller</h3>
@Html.ActionLink("Back to Home controller", "index", "Home")<br /><br />

<h4>Data from View component controller</h4>
<vc:posted-data />
<br />

<h4>Data from database</h4>
<table>
    <tr>
        <th>Post ID</th>
        <th>Post content</th>
        <th>Post date time</th>
    </tr>
    @foreach (var post in Model.Posts)
    {
        <tr>
            <td>@post.id</td>
            <td>@post.post</td>
            <td>@post.postedDateTime</td>
        </tr>
    }
</table>